split Review to container, component and ReviewEdit
ivan-education/react-20231109 pull request #12
Opened 2023-12-17 17:27 UTC by ivan-education

2023-12-18 14:45 UTC, SArchieEdu requested changes

2023-12-18 14:45 UTC, SArchieEdu commented on src/components/review-edit/component.tsx
> +  const [newRating, setNewRating] = useState(rating);
у нас уже был пример через редьюсер, он тут уместнее

2023-12-18 14:45 UTC, SArchieEdu commented on src/components/review-edit/component.tsx
> +  });
для этого есть useEffect

2023-12-23 10:58 UTC, ivan-education commented on src/components/review-edit/component.tsx
> +  const [newRating, setNewRating] = useState(rating);
@SArchieEdu  Добавил. Но было бы здорово, если б ты пояснил, почему даже для такого случая редьюсер предпочтительнее. Все-таки это намного больше кода и сложнее.

2023-12-23 10:59 UTC, ivan-education commented on src/components/review-edit/component.tsx
> +  });
Оказалось, вообще достаточно добавить autofocus и все работает

2024-01-14 10:27 UTC, SArchieEdu approved these changes

2024-01-14 12:52 UTC, merged