lecture 3: hw
ivan-education/react-20231109 pull request #3
Opened 2023-11-21 20:34 UTC by ivan-education

2023-11-23 12:04 UTC, SArchieEdu requested changes

2023-11-23 12:04 UTC, SArchieEdu commented on src/components/dish/component.tsx
> +  };
Этот стейт дублирует стейт счетчика, на разборе покажу как сделать иначе

2023-11-23 13:00 UTC, ivan-education commented on src/components/dish/component.tsx
> +  };
Сделал Counter stateless

2023-11-30 13:54 UTC, ArchieSA approved these changes

2023-11-30 15:31 UTC, merged