create Layout and scss/styles
ivan-education/react-20231109 pull request #7
Opened 2023-12-02 13:50 UTC by ivan-education

2023-12-04 14:54 UTC, SArchieEdu requested changes

2023-12-04 14:54 UTC, SArchieEdu commented on src/components/layout/component.tsx
> +  const [theme, setTheme] = useState<Theme>(Theme.LIGHT);
любое изменение темы будут перерендеривать всю страницу, профит от контекста уменьшается. Лучше использовать псевдородители как в лекции

2023-12-05 16:18 UTC, ivan-education commented on src/components/layout/component.tsx
> +  const [theme, setTheme] = useState<Theme>(Theme.LIGHT);
Добавил. Изменил подход

2023-12-07 15:09 UTC, SArchieEdu approved these changes

2023-12-07 15:17 UTC, merged